### ISSUE TITLE
hook an event when a pull request is closed

### ISSUE THREAD

**Issue by tosite** [k1LoW/ghdag#75]
Hello, @k1LoW.

Thank you for the nice OSS.
I use it conveniently.

By the way, I would like to ask you if you currently do not support "When a pull request is closed" as an event trigger? 
Also, is there any plan to support it in the future?
(Intended use case: I want to give a label to a pull request when it is closed.)

The "Issues and pull requests fetched by ghdag" says: 
> A single opened and not drafted pull request that triggered the event

Best Regards.

**Comment by k1LoW** [comment]
Thanks for using ghdag!

> By the way, I would like to ask you if you currently do not support "When a pull request is closed" as an event trigger?

It is probably difficult.
This is because ghdag defines a pull request or Issue close as the end of the DAG.

**Comment by k1LoW** [comment]
ghdag does not look at events, only the current status of Pull Requests and Issues.
It can't do anything because ghdag considers a pull request that has ended to be a DAG that has ended.

**Comment by tosite** [comment]
Thanks for your reply.

> ghdag considers a pull request that has ended to be a DAG that has ended.

I see, I understand.
This time I would like to get the event after Close in a different way.

I will be grateful for your continued use. I will support you.

**Comment by tosite** [comment]
I have given up on comment or labeling by ghdag for pull requests after Close.
However, using https://github.com/k1LoW/github-script-ruby solved the problem.
Thank you!
